
const worksheetValues = [
  'period',
  'activity_period',
  'retailer',
  'territory', 
  'orchard_upc', 
  'manufacture_upc',
  'project_code', 
  'product_code',
  'sub_account',
  'imprint_label',
  'artist_name',
  'product_name',
  'track_name',
  'track_artist',
  'isrc',
  'volume',
  'track_integer',
  'trans_type',
  'trans_type_description', 
  'unit_price', 
  'discount',
  'actual_price',
  'quantity',
  'total',
  'adjusted_total',
  'split_rate',
  'label_share_net_receipts',
  'ringtone_publishing',
  'cloud_publishing',
  'publishing',
  'mech_admin_fee',
  'preferred_currency',
]

const worksheetColumns = [
  {key: 'period'},
  {key: 'activity_period'},
  {key: 'retailer'},
  {key: 'territory'},
  {key: 'orchard_upc'},
  {key: 'manufacture_upc'},
  {key: 'project_code'},
  {key: 'product_code'},
  {key: 'sub_account'},
  {key: 'imprint_label'},
  {key: 'artist_name'},
  {key: 'product_name'},
  {key: 'track_name'},
  {key: 'track_artist'},
  {key: 'isrc'},
  {key: 'volume'},
  {key: 'track_integer'},
  {key: 'trans_type'},
  {key: 'trans_type_description'},
  {key: 'unit_price'},
  {key: 'discount'},
  {key: 'actual_price'},
  {key: 'quantity'},
  {key: 'total'},
  {key: 'adjusted_total'},
  {key: 'split_rate'},
  {key: 'label_share_net_receipts'},
  {key: 'ringtone_publishing'},
  {key: 'cloud_publishing'},
  {key: 'publishing'},
  {key: 'mech_admin_fee'},
  {key: 'preferred_currency'}
]

module.exports = { worksheetValues, worksheetColumns }